# Enhanced DataTobiz Brand Monitoring Configuration (Stage 2)
# SECURE VERSION - Uses environment variables for sensitive data

# LLM Configurations
llm_configs:
  openai:
    name: "openai"
    api_key: "${OPENAI_API_KEY}"
    model: "gpt-4o"
    max_tokens: 2000
    temperature: 1.0
    timeout: 30

  perplexity:
    name: "perplexity"
    api_key: "${PERPLEXITY_API_KEY}"
    model: "sonar"
    max_tokens: 2000
    temperature: 1.0
    timeout: 30

  gemini:
    name: "gemini"
    api_key: "${GEMINI_API_KEY}"
    model: "gemini-pro"
    max_tokens: 1000
    temperature: 0.1
    timeout: 30

# Google Sheets Configuration
google_sheets:
  spreadsheet_id: "${GOOGLE_SPREADSHEET_ID}"
  worksheet_name: "Brand_Monitoring_New"
  credentials_file: "./credentials.json"  # Will use Streamlit secrets in production
  auto_setup_headers: true
  batch_size: 10
  enable_validation: true

# Brand Configuration
brand:
  target_brand: "DataTobiz"
  brand_variations:
    - "DataTobiz"
    - "Data Tobiz"
    - "data tobiz"
    - "DATATOBIZ"
    - "DataToBiz"
    - "Data-Tobiz"
    - "datatobiz.com"
  case_sensitive: false
  partial_match: true

# Workflow Configuration
workflow:
  max_retries: 3
  retry_delay: 1.0
  parallel_execution: true
  timeout_per_agent: 60
  log_level: "INFO"

# Stage 2 Configuration
stage2:
  enable_ranking_detection: true
  enable_cost_tracking: true
  enable_analytics: true
  ranking_detection:
    max_position: 20
    min_confidence: 0.6
    enable_ordinal_detection: true
    enable_list_detection: true
    enable_keyword_detection: true
    enable_numeric_detection: true

# Enhanced Brand Configuration
enhanced_brand:
  context_analysis:
    context_window: 200
    enable_sentiment_analysis: false
    positive_keywords:
      - "excellent"
      - "outstanding"
      - "innovative"
      - "reliable"
      - "powerful"
      - "comprehensive"
      - "award-winning"
      - "recognized"
      - "trusted"
      - "proven"
    negative_keywords:
      - "poor"
      - "disappointing"
      - "limited"
      - "lacking"
      - "outdated"
      - "problematic"
  structure_detection:
    detect_in_lists: true
    detect_near_headings: true
    detect_comparisons: true

# Analytics Configuration
analytics:
  enabled: true
  metrics:
    - "detection_rate"
    - "ranking_positions"
    - "confidence_scores"
    - "execution_times"
    - "cost_tracking"
    - "agent_performance"
  daily_reports: false
  weekly_summaries: true
  trend_analysis: true
  retention_days: 365

# Security Configuration
security:
  validate_api_keys: true
  enable_rate_limiting: true
  rate_limits:
    openai: 50
    perplexity: 20
    gemini: 60
  log_requests: false
  mask_api_keys: true